seed_everything: 42

trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: bf16-mixed

  max_epochs: 1
  accumulate_grad_batches: 4
  log_every_n_steps: 1

  default_root_dir: ./projects
  use_distributed_sampler: true

  fast_dev_run: true # disable to actually train

  logger:
    - class_path: lightning.pytorch.loggers.wandb.WandbLogger
      init_args:
        project: neurosis-test
        save_dir: ${trainer.default_root_dir}
        tags: [sd15, test]
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: ${trainer.default_root_dir}
        name: neurosis-test

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 5
    - class_path: DeviceStatsMonitor
      init_args:
        cpu_stats: true

model_checkpoint:
  filename: "{epoch:03d}-{step:08d}"
  save_last: true
  save_on_train_epoch_end: true
  every_n_train_steps: 250
  verbose: true

image_logger:
  every_n_train_steps: 50
  max_images: 4
  clamp: true
  rescale: true
  log_step_type: global_step # global_step, batch_idx, global_batch, sample_idx (see neurosis.trainer.callbacks.image_logger)
  log_before_start: false
  log_func_kwargs:
    num_img: 4

model:
  class_path: neurosis.models.DiffusionEngine
  init_args:
    scale_factor: 0.18215
    disable_first_stage_autocast: true
    log_keys:
      - caption
    ckpt_path: data/sd15/UMMdromedaDX-A.neurosis.safetensors
    use_ema: false
    input_key: ${data.init_args.image_key}
    no_cond_log: false
    compile_model: false

    model:
      class_path: neurosis.modules.diffusion.UNetModel
      init_args:
        use_checkpoint: true
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_heads: 8
        transformer_depth: 1
        context_dim: 768
        spatial_transformer_attn_type: softmax-xformers

    denoiser:
      class_path: neurosis.modules.diffusion.DiscreteDenoiser
      init_args:
        num_idx: 1000
        preconditioning:
          class_path: neurosis.modules.diffusion.EpsPreconditioning
        discretization:
          class_path: neurosis.modules.diffusion.LegacyDDPMDiscretization

    first_stage_model:
      class_path: neurosis.models.autoencoder.AutoencoderKL
      init_args:
        ckpt_path: data/sd15/kl-f8-anime2.vae.pt
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          attn_type: vanilla-xformers
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        loss:
          class_path: torch.nn.Identity

    conditioner:
      class_path: neurosis.modules.encoders.GeneralConditioner
      init_args:
        emb_models:
          - class_path: neurosis.models.text_encoder.FrozenCLIPEmbedder
            init_args:
              layer: hidden
              layer_idx: 11
              input_key: ${data.init_args.caption_key}
              is_trainable: false

    optimizer:
      # you can replace this with any subclass of torch.optim.Optimizer
      class_path: neurosis.optimizers.Adafactor
      init_args:
        scale_parameter: true
        relative_step: true
        warmup_init: true

    scheduler:
      class_path: neurosis.optimizers.AdafactorScheduler
      init_args:
        initial_lr: 4e-7

    loss_fn:
      class_path: neurosis.modules.diffusion.StandardDiffusionLoss
      init_args:
        loss_weighting:
          class_path: neurosis.modules.diffusion.EpsWeighting
        sigma_generator:
          class_path: neurosis.modules.diffusion.sigma_sampling.DiscreteSampling
          init_args:
            num_idx: 1000
            discretization:
              class_path: neurosis.modules.diffusion.LegacyDDPMDiscretization

    sampler:
      class_path: neurosis.modules.diffusion.sampling.EulerEDMSampler
      init_args:
        num_steps: 50
        discretization:
          class_path: neurosis.modules.diffusion.LegacyDDPMDiscretization
        guider:
          class_path: neurosis.modules.guidance.VanillaCFG
          init_args:
            scale: 7.5

data:
  class_path: neurosis.dataset.imagefolder.ImageFolderModule
  init_args:
    folder: "data/dataset/folder"
    recursive: true
    image_key: "image"
    caption_key: "caption"
    buckets:
      class_path: neurosis.dataset.aspect.WDXLBucketList
      init_args:
        bias_square: true
        use_atan: false
    batch_size: 2
    num_workers: 4
    tag_sep: ", "
    word_sep: " "
