name: Container Build Test
run-name: neurosis (test)

on:
  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-base
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@v4
        with:
          target: neurosis

  validate:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        uses: docker/bake-action@v4
        with:
          targets: ${{ matrix.target }}
